version: "3.6"
services:
  wannadb:
    build:
      context: .
      dockerfile: Dockerfile-backend
    restart: always
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: 0
      POSTGRES_DB: userManagement
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata: